// <auto-generated />
using System;
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.LotrCardModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsGreatHappening")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLotrOrTheHobbit")
                        .HasColumnType("bit");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TimeValue")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Trivia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LotrCard");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 40000,
                            Category = "Lord of The Rings",
                            Day = 25,
                            Difficulty = 0,
                            IsGreatHappening = true,
                            IsLotrOrTheHobbit = true,
                            Month = 3,
                            Question = "The One Ring is destroyed in Mount Doom",
                            TimeValue = 43019.085m,
                            Trivia = "Trivia about The Ring",
                            Year = 3019
                        },
                        new
                        {
                            Id = 2,
                            Age = 40000,
                            Category = "Lord of The Rings",
                            Day = 22,
                            Difficulty = 0,
                            IsGreatHappening = true,
                            IsLotrOrTheHobbit = true,
                            Month = 9,
                            Question = "Frodo is born",
                            TimeValue = 42968.262m,
                            Trivia = "Trivia about Frodo",
                            Year = 2968
                        },
                        new
                        {
                            Id = 3,
                            Age = 40000,
                            Category = "Lord of The Rings",
                            Day = 1,
                            Difficulty = 0,
                            IsGreatHappening = true,
                            IsLotrOrTheHobbit = true,
                            Month = 3,
                            Question = "Aragorn is born",
                            TimeValue = 42931.061m,
                            Trivia = "Aragorns birth name was Estel",
                            Year = 2931
                        },
                        new
                        {
                            Id = 4,
                            Age = 30000,
                            Category = "Lord of The Rings",
                            Difficulty = 0,
                            IsLotrOrTheHobbit = false,
                            Question = "The One Ring is made",
                            TimeValue = 31600m,
                            Trivia = "Trivia about The One Ring",
                            Year = 1600
                        },
                        new
                        {
                            Id = 5,
                            Age = 30000,
                            Category = "Lord of The Rings",
                            Difficulty = 0,
                            IsLotrOrTheHobbit = true,
                            Question = "Death of Celebrimbor",
                            TimeValue = 31697m,
                            Trivia = "Celebrimbor is the grandson of Fëanor",
                            Year = 1697
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
